### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [msimonides/homerplayer#15]
Would you mind publishing the `.apk` file here at Github along with your `releases/` – so it gets available also for folks with no Playstore access? I'd then make it available for easier install/update via [my F-Droid compatible repo](https://android.izzysoft.de/repo) :smiley_cat:

Thanks in advance!

**Comment by msimonides** [comment]
Done :)

**Comment by IzzySoft** [comment]
Thanks a lot! [Keeping my promise](https://apt.izzysoft.de/fdroid/index/apk/com.studio4plus.homerplayer), so feel free to link an F-Droid logo there :)

**Comment by IzzySoft** [comment]
Looks like you forgot it again with v0.6.1. :scream_cat: Could you please fill that gap? Thanks in advance!

**Comment by msimonides** [comment]
Looks like I didn't but there was an error indicator near the file on GitHub :-/
Uploaded again. And uploaded the 0.6.2 release as well ;-P`

**Comment by IzzySoft** [comment]
Oops… Well, happens :smile_cat: Updater just picked v0.6.2 (and skipped v0.6.1) – repo up-to-date again, thanks!
